//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long TransId { get; set; }
        public string Host { get; set; }
        public string LogTime { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string MethodName { get; set; }
        public string ExpType { get; set; }
        public string ExDetail { get; set; }
    }
}
